[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bichocoin_program = "8rptyeuewV5niejZieWhjS4Uc8hXJp5FMbpDrk3RyUZt"

[programs.devnet]
bichocoin_program = "8rptyeuewV5niejZieWhjS4Uc8hXJp5FMbpDrk3RyUZt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
